### ISSUE TITLE
info

### ISSUE THREAD

**Issue by CodyDeeds** [evm2p/steem-fossbot-voter#1]
ad some info for entering the password, was not sure how to use initially 

![dashboard voter](https://cloud.githubusercontent.com/assets/10130552/22298713/7fd30268-e2ef-11e6-8fe0-86120c66137a.png)

**Comment by evm2p** [comment]
Good catch, will add that

**Comment by evm2p** [comment]
Finished this improvement as of a624e15

Starting a session with your BOT_API_KEY is now handled by a form and stays on the dashboard. When a valid session is active, a message will be shown here to confirm that fact, otherwise the start session form is shown.

**Comment by CodyDeeds** [comment]
Wow that was fast, thank you.

**Comment by evm2p** [comment]
Well you happened to catch me in a period of busy bug fixing! Thanks for the feedback

**Comment by CodyDeeds** [comment]
active devs are priceless
